server:
  port:8080


spring:
  application:
    name: SoftwareGaze-Portal

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

frontend:
  url: ${FRONTEND_URL}


#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false



logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    com.example.auth: DEBUG